services:
  ollama-app:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    ports:
      - "8000:11434"
    volumes:
      - ./ollama/entrypoint.sh:/entrypoint.sh:ro
      - ollama-models:/root/.ollama

volumes:
  ollama-models:
